# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - test

# NEW
variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules
# END NEW
# Jobs 
install_dependencies:
  stage: install
  script:
    - npm ci

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

build_jobX:
  stage: build
  only:
    - demobranch
  script:
    - echo "build job X on demoBranch works"
    
e2etest:    
  stage: test
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
    # start the server in the background
    - npm run start:ci